version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
  doctorcare:
    build:
      context: ./doctorcare
      dockerfile: Dockerfile